/**
 * FoodBucket
 * This is a server API for FoodBucket project
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@foodbucket.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Ingredient {
    ingredientId?: number;

    title: string;

    description: string;

    image: string;

    measure?: string;

    quantity?: string;

    price?: number;

    discount?: number;

}
