/**
 * FoodBucket
 * This is a server API for FoodBucket project
 *
 * OpenAPI spec version: 0.0.1
 * Contact: support@foodbucket.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Register {
    userId?: number;

    email: string;

    password: string;

    firstName: string;

    lastName: string;

    city?: string;

    address?: string;

}
